---
- name: 'Deploy Docker DB Backupper'
  docker_swarm_service:
    name: 'db_backup'
    command: >
    "sh -c 'while true;
      do
        for container in $(docker ps -qf name=mariadb);
        do
          docker exec $container /usr/bin/mysqldump -A -u root --password={{ db_root_password }} > /var/lib/mysql/backup.sql;
        done;
        sleep {{ docker_db_backup_delay }};
      done'"
    image: 'docker'
    mounts:
      - source: '/var/run/docker.sock'
        target: '/var/run/docker.sock'
        type: 'bind'
    mode: 'global'
    restart_config:
      condition: 'any'
    placement:
      constraints:
        - 'node.platform.os == linux'
    user: null
