---
- name: 'Create directory for container data'
  ansible.builtin.file:
    path: "{{ docker_data_dir }}/{{ dir }}"
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'
  loop:
    - 'janitor_data'
  loop_control:
    loop_var: 'dir'

- name: 'Place files for Janitor'
  ansible.builtin.template:
    src: 'clean_docker.sh.j2'
    dest: "{{ docker_data_dir }}/janitor_data/clean_docker.sh"
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: 'Deploy Docker Janitor'
  community.docker.docker_swarm_service:
    name: 'janitor'
    command: '/clean_docker.sh'
    image: 'docker'
    mounts:
      - source: '/var/run/docker.sock'
        target: '/var/run/docker.sock'
        type: 'bind'
      - source: "{{ docker_data_dir }}/janitor_data/clean_docker.sh"
        target: '/clean_docker.sh'
        type: 'bind'
    mode: 'global'
    restart_config:
      condition: "{{ restart_condition }}"
    placement:
      constraints:
        - 'node.platform.os == linux'
    user: null
