---
- name: 'Set up Docker Swarm'
  include_tasks: 'docker_swarm.yml'

- name: "Deploy services"
  include_tasks: "{{ container }}.yml"
  loop:
    - "{{ mandatory_services }}"
    - "{{ enabled_services | default([]) }}"
  loop_control:
    loop_var: 'container'
