---
- name: 'Create network'
  docker_network:
    name: 'rocketchat_backend'
    driver: 'overlay'

- name: 'Create directory for container data'
  file:
    path: "{{ docker_data_dir }}/{{ dir.name }}"
    owner: "{{ dir.owner | default('0') }}"
    state: 'directory'
  loop:
    - {name: 'rocketchat_db/db'}
    - {name: 'rocketchat_db/dump'}
    - {name: 'rocketchat_data'}
  loop_control:
    loop_var: 'dir'

- name: 'Deploy Mongo for Rocket.Chat'
  docker_swarm_service:
    name: 'rocketchat_mongo'
    image: 'mongo:3.0'
    mounts:
      - source: "{{ docker_data_dir }}/rocketchat_db/db"
        target: '/data/db'
        type: 'bind'
      - source: "{{ docker_data_dir }}/rocketchat_db/dump"
        target: '/dump'
        type: 'bind'
    networks:
      - 'rocketchat_backend'
    mode: 'replicated'
    replicas: 1
    restart_config:
      condition: "{{ restart_condition }}"
    user: null

- name: 'Deploy Rocket.Chat'
  docker_swarm_service:
    name: 'rocketchat'
    image: 'rocket.chat'
    command: bash -c 'for i in `seq 1 30`; do node main.js && s=$$? && break || s=$$?; echo "Tried $$i times. Waiting 5 secs..."; sleep 5; done; (exit $$s)'
    env:
      - 'PORT=3000'
      - "ROOT_URL=https://{{ rocketchat_app_name }}.{{ traefik_domain }}"
      - 'MONGO_URL=mongodb://rocketchat_mongo:27017/rocketchat'
      - 'MONGO_OPLOG_URL=mongodb://rocketchat_mongo:27017/local'
      - 'Accounts_UseDNSDomainCheck=True'
    networks:
      - 'rocketchat_backend'
    labels:
      traefik.port: '3000'
      traefik.docker.network: 'traefik_backend'
      traefik.frontend.rule: "Host:{{ rocketchat_app_name }}.{{ traefik_domain }}"
    mounts:
      - source: "{{ docker_data_dir }}/rocketchat_data"
        target: '/app/uploads'
        type: 'bind'
    mode: 'replicated'
    replicas: 1
    restart_config:
      condition: "{{ restart_condition }}"
    user: null
