---
- name: 'Create network'
  docker_network:
    name: 'wikijs_backend'
    driver: 'overlay'

- name: 'Create directory for container data'
  file:
    path: "{{ docker_data_dir }}/{{ dir }}"
    state: 'directory'
  loop:
    - 'wikijs_db'
    - 'wikijs_data/data'
    - 'wikijs_data/repo'
    - 'wikijs_data/ssh'
  loop_control:
    loop_var: 'dir'

- name: 'Deploy MariaDB for Wiki.js'
  docker_swarm_service:
    name: 'wikijs_mariadb'
    image: 'mariadb'
    env:
      - "MYSQL_ROOT_PASSWORD={{ db_root_password }}"
      - 'MYSQL_DATABASE=wikijs'
      - 'MYSQL_USER=wikijs'
      - "MYSQL_PASSWORD={{ wikijs_db_password }}"
    mounts:
      - source: "{{ docker_data_dir }}/wikijs_db"
        target: '/data/db'
        type: 'bind'
    networks:
      - 'wikijs_backend'
    mode: 'replicated'
    replicas: 1
    restart_config:
      condition: 'any'
    user: null

- name: 'Deploy Wiki.js'
  docker_swarm_service:
    name: 'wikijs'
    image: 'requarks/wiki:beta'
    networks:
      - 'wikijs_backend'
      - 'traefik_backend'
    env:
      - "WIKI_ADMIN_EMAIL={{ wikijs_init_admin_email }}"
      - 'DB_TYPE=mariadb'
      - 'DB_HOST=tasks.wikijs_mariadb'
      - 'DB_PORT=3306'
      - 'DB_NAME=wikijs'
      - 'DB_USER=wikijs'
      - "DB_PASSWORD={{ wikijs_db_password }}"
    mounts:
      - source: "{{ docker_data_dir }}/wikijs_data/data"
        target: '/var/wiki/data'
        type: 'bind'
      - source: "{{ docker_data_dir }}/wikijs_data/repo"
        target: '/var/wiki/repo'
        type: 'bind'
      - source: "{{ docker_data_dir }}/wikijs_data/ssh"
        target: '/var/wiki/ssh'
        type: 'bind'
      - source: "{{ docker_data_dir }}/wikijs_data/config.yml"
        target: '/wiki/config.yml'
        type: 'bind'
    labels:
      traefik.port: '3000'
      traefik.docker.network: 'traefik_backend'
      traefik.frontend.rule: "Host:{{ wikijs_app_name }}.{{ traefik_domain }}"
    mode: 'replicated'
    replicas: 1
    restart_config:
      condition: 'any'
    user: null
